kind: ConfigMap
apiVersion: v1
metadata:
  name: home-index-file
  namespace: tooling
data:
  index.html: |
    <html>
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
          crossorigin="anonymous"
        />
        <script
          async
          src="https://ga.jspm.io/npm:es-module-shims@1.5.6/dist/es-module-shims.js"
        ></script>
        <style>
          body {
            padding: 3rem 1rem;
          }
        </style>
        <title>kube-dev</title>
      </head>
      <body>
        <div class="container">
          <h1>Welcome to kube-dev</h1>
          <p>A collection of useful links</p>
          <div id="cards"></div>
        </div>
      </body>
      <script>
        const renderCard = (data) => `
    <div class="card" >
      <div class="card-body">
        <h5 class="card-title">${data.title}</h5>
        <h6 class="card-subtitle mb-2 text-body-secondary">${
          data.subtitle || ""
        }</h6>
        <p class="card-text">${data.description || ""}</p>
        <a href="${data.url}" class="btn btn-info">Open</a>
      </div>
    </div>
    `;
        const cards = [
          {
            title: "ArgoCD",
            subtitle: "GitOps cluster management",
            url: "https://argo.kube-dev.incubateur.net",
          },
          {
            title: "GitHub repository",
            subtitle: "The ArgoCD source repo",
            url: "https://github.com/betagouv/kube-dev",
          },
          {
            title: "Kube Resource Report",
            subtitle: "Cluster ressource allocations dashboard",
            url: "https://krr.kube-dev.incubateur.net/",
          },

          {
            title: "Vault",
            subtitle: "Secrets management",
            url: "https://vault.kube-dev.incubateur.net",
          },
          {
            title: "Grafana",
            subtitle: "Logs, Metrics and supervision",
            url: "https://grafana.kube-dev.incubateur.net",
          },
        ];

        const html = `<div class="row row-cols-1 g-4" >${cards
          .map(renderCard)
          .join("\n")}</div>`;

        document.getElementById("cards").innerHTML = html;
      </script>
    </html>
