#https://github.com/elastic/cloud-on-k8s/tree/2.14/deploy/eck-stack

eck-stack:
  eck-elasticsearch:
    fullnameOverride: elk1-elasticsearch
    ingress:
      hosts:
        - host: "elastic.elk1.kube-dev.incubateur.net"
          path: "/"
  eck-kibana:
    fullnameOverride: elk1-kibana
    spec:
      elasticsearchRef:
        name: elk1-elasticsearch
      config:
        server:
          publicBaseUrl: "https://kibana.elk1.kube-dev.incubateur.net"
    ingress:
      hosts:
        - host: "kibana.elk1.kube-dev.incubateur.net"
          path: "/"
  eck-apm-server:
    fullnameOverride: elk1-apm
    elasticsearchRef:
      name: elk1-elasticsearch
    kibanaRef:
      name: elk1-kibana
  eck-logstash:
    fullnameOverride: elk1-logstash
    elasticsearchRefs:
      - name: "elk1-elasticsearch"
        #namespace: ''
        #clusterName: ''
        #serviceName: ''
        #secretName: ''
  eck-beats:
    enabled: true
    fullnameOverride: elk1-beats
    spec:
      type: filebeat
      daemonSet: null
      deployment:
        replicas: 1
        strategy:
          type: Recreate
      elasticsearchRef:
        name: elk1-elasticsearch
      kibanaRef:
        name: elk1-kibana
