#https://github.com/elastic/cloud-on-k8s/tree/2.14/deploy/eck-stack

eck-stack:
  eck-elasticsearch:
    fullnameOverride: elk1-elasticsearch
    ingress:
      hosts:
        - host: "elastic.elk1.kube-dev.incubateur.net"
          path: "/"
  eck-kibana:
    fullnameOverride: elk1-kibana
    spec:
      elasticsearchRef:
        name: elk1-elasticsearch
      config:
        server:
          publicBaseUrl: "https://kibana.elk1.kube-dev.incubateur.net"
    ingress:
      hosts:
        - host: "kibana.elk1.kube-dev.incubateur.net"
          path: "/"
  eck-apm-server:
    fullnameOverride: elk1-apm
    elasticsearchRef:
      name: elk1-elasticsearch
    kibanaRef:
      name: elk1-kibana
  eck-logstash:
    fullnameOverride: elk1-logstash
    elasticsearchRefs:
      - name: "elk1-elasticsearch"
        clusterName: "elk1-elasticsearch"
        #namespace: ''
        #serviceName: ''
        #secretName: ''
  eck-beats:
    enabled: true
    fullnameOverride: elk1-beats
    spec:
      type: filebeat
      daemonSet:
        podTemplate:
          spec:
            automountServiceAccountToken: true
            terminationGracePeriodSeconds: 30
            dnsPolicy: ClusterFirstWithHostNet
            hostNetwork: true # Allows to provide richer host metadata
            containers:
              - name: filebeat
                securityContext:
                  runAsUser: 0
                  # If using Red Hat OpenShift uncomment this:
                  #privileged: true
                volumeMounts:
                  - name: varlogcontainers
                    mountPath: /var/log/containers
                  - name: varlogpods
                    mountPath: /var/log/pods
                  - name: varlibdockercontainers
                    mountPath: /var/lib/docker/containers
            volumes:
              - name: varlogcontainers
                hostPath:
                  path: /var/log/containers
              - name: varlogpods
                hostPath:
                  path: /var/log/pods
              - name: varlibdockercontainers
                hostPath:
                  path: /var/lib/docker/containers
      # daemonSet: null
      # deployment:
      #   replicas: 1
      #   strategy:
      #     type: Recreate
      elasticsearchRef:
        name: elk1-elasticsearch
      kibanaRef:
        name: elk1-kibana
      config:
        filebeat.inputs:
          - type: container
            paths:
              - /var/log/containers/*.log
        processors:
          - add_host_metadata: {}
          - add_cloud_metadata: {}
