apiVersion: v1
kind: Service
metadata:
  labels:
    app: albert-api
  name: albert-api
  namespace: tooling
spec:
  type: ExternalName
  externalName: albert.api.etalab.gouv.fr
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: albert-api
  namespace: tooling
  labels:
    app: albert-api
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/upstream-vhost: https://albert.api.etalab.gouv.fr
    nginx.ingress.kubernetes.io/enable-cors: "true"

spec:
  rules:
    - host: albert-api.kube-dev.incubateur.net
      http:
        paths:
          - backend:
              service:
                name: home
                port:
                  name: https
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - albert-api.kube-dev.incubateur.net
      secretName: albert-api-tls-secret
