oauth2-proxy:
  ingress:
    enabled: true
    path: /
    hosts:
      - oauth.kube-dev.incubateur.net
    annotations:
      kubernetes.io/ingress.class: external
      cert-manager.io/cluster-issuer: letsencrypt-prod
    tls:
      - hosts:
          - oauth.kube-dev.incubateur.net