apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-storage
spec:
  storageClassName: csi-cinder-high-speed
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi