# https://github.com/pmint93/helm-charts/blob/master/charts/metabase/values.yaml

image:
  tag: v0.55.4.3

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-response-headers:
      X-Auth-Request-Email,X-Auth-Request-Preferred-,X-Auth-Request-Access-Token,
      X-Auth-Request-Roles,X-Auth-Request-User,X-Auth-Request-Groups,X-Forwarded-Groups,
      Authorization
    nginx.ingress.kubernetes.io/auth-signin: https://oauth.kube-dev.incubateur.net/oauth2/start?rd=https%3A%2F%2F$host$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-url: https://oauth.kube-dev.incubateur.net/oauth2/auth
  tls:
    # Secrets must be manually created in the namespace.
    - secretName: metabase-tls
      hosts: []

resources:
  limits:
    cpu: 2
    memory: 2Gi
  requests:
    cpu: 200m
    memory: 256Mi
