# https://github.com/pmint93/helm-charts/blob/master/charts/metabase/values.yaml

envFrom:
  - type: secret
    name: metabase # provided by manifests folders for the dedicated MB_ENCRYPTION_SECRET_KEY
  - type: secret
    name: smtp-creds

extraEnv:
  - name: PG_PASSWORD
    valueFrom:
      secretKeyRef:
        name: pg-matomo-beta
        key: postgres-password
  - name: MB_DB_CONNECTION_URI
    value: "postgres://pg-matomo-beta:5432/postgres?user=postgres&password=$(PG_PASSWORD)"
