# https://github.com/bitnami/charts/blob/main/bitnami/postgresql/README.md

nameOverride: pg-test1

primary:
  resourcesPreset: "small"

  extraVolumeMounts:
    - name: matomo-to-pg-languia-initdb
      mountPath: /docker-entrypoint-initdb.d
      readOnly: true

  extraVolumes:
    - name: matomo-to-pg-languia-initdb
      configMap:
        name: matomo-to-pg-languia-initdb