kind: ConfigMap
apiVersion: v1
metadata:
  name: test-pc-index-file
  namespace: tooling
data:
  index.html: |
    <html>
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
          crossorigin="anonymous"
        />
        <script
          async
          src="https://ga.jspm.io/npm:es-module-shims@1.5.6/dist/es-module-shims.js"
        ></script>
        <style>
          body {
            padding: 3rem 1rem;
          }
        </style>
        <title>test-pc</title>
      </head>
      <body>
        <div class="container">
          <h1>Welcome to test-pc</h1>
          <p>Testing pro-connect integration</p>
          <div id="cards"></div>
        </div>
      </body>
      <script>
      </script>
    </html>
