apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
spec:
  project: animation
  destination:
    server: https://kubernetes.default.svc
    namespace: immich
  source:
    repoURL: https://immich-app.github.io/immich-charts
    targetRevision: 0.8.1
    chart: immich
    helm:
      # https://github.com/immich-app/immich-charts/blob/main/charts/immich/values.yaml
      values: |
        image:
          tag: v1.116.0
        immich:
          configuration:
            logging:
              enabled: true
              level: debug
            server:
              externalDomain: "https://immich.kube-dev.incubateur.net"
              loginPageMessage: "Welcome home"
          metrics:
            enabled: true
          persistence:
            library:
              existingClaim: "immich-storage"
        server:
          env:
            IMMICH_LOG_LEVEL: debug
            IMMICH_PORT: 3001
            TZ: "Europe/Paris"  
          resources:
            limits:
              cpu: 2
              memory: 512Mi
            requests:
              cpu: 300m
              memory: 256Mi
          ingress:
            main:
              enabled: true
              ingressClassName: nginx
              annotations:
                nginx.ingress.kubernetes.io/proxy-body-size: '10M'
                nginx.ingress.kubernetes.io/proxy-read-timeout: '3600'
                nginx.ingress.kubernetes.io/proxy-send-timeout: '3600'
              hosts:
                - host: immich.kube-dev.incubateur.net
                  paths:
                    - path: "/"
              tls:
               - hosts:                                                                                                                                                                                                                                        
                 - immich.kube-dev.incubateur.net
                 secretName: immich-tls-secret
        postgresql:
          enabled: true
          resources:
            limits:
              cpu: 800m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
        redis:
          enabled: true

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: false # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
