apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-resource-report
  namespace: argocd
spec:
  project: animation
  destination:
    server: https://kubernetes.default.svc
    namespace: tooling
  source:
    repoURL: https://rlex.github.io/helm-charts
    targetRevision: 0.10.1
    chart: kube-resource-report
    helm:
      values: |
        image:
          tag: 22.11.0
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod                                                                                                                                                                                              
            kubernetes.io/ingress.class: nginx
          hosts:
            - host: krr.kube-dev.incubateur.net
              paths:
                - path: "/"
                  pathType: Prefix
          tls:
          - hosts:                                                                                                                                                                                                                                        
            - krr.kube-dev.incubateur.net
            secretName: krr-tls-secret 

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: false # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
