apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: oauth2-routes
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          # add the urls you want to protect with oauth2/github betagouv organisation
          # these urls should be accessible by 57.128.17.152, 193.70.74.46, 217.182.104.248
          # todo: use OVH load balancer for fixed outbound IP or use CNAMES
          - id: httpbin-proxy
            host: httpbin.kube-dev.incubateur.net
            target_host: httpbin.org
            target_port: 443
          - id: demo-proxy
            host: demo-proxy.kube-dev.incubateur.net
            target_host: b932b288-0371-4948-a0c5-ceb8cf72f3c7.pub.instances.scw.cloud
            target_port: 80
          # - id: metabase-proxy
          #   host: metabase.kube-dev.incubateur.net
          #   target_host: metabase.incubateur.net
  goTemplate: true
  template:
    metadata:
      name: "oauth2-{{.id}}"
    spec:
      project: tooling
      sources:
        - repoURL: https://github.com/betagouv/kube-dev
          targetRevision: HEAD
          path: oauth2-routes
          kustomize:
            patches:
              - target:
                  kind: Ingress
                # https://github.com/kubernetes-sigs/kustomize/issues/1256#issuecomment-535007229
                patch: |-
                  - op: replace
                    path: "/metadata/annotations/nginx.ingress.kubernetes.io~1upstream-vhost"
                    value: "{{.target_host}}"
                  - op: replace
                    path: "/metadata/annotations/nginx.ingress.kubernetes.io~1backend-protocol"
                    value: "{{ if eq .target_port 80 }}HTTP{{ else }}HTTPS{{ end }}"
                  - op: replace
                    path: /metadata/labels/app
                    value: "oauth2-{{.id}}"
                  - op: replace
                    path: /metadata/name
                    value: "oauth2-{{.id}}"
                  - op: replace
                    path: /spec/rules/0/host
                    value: "{{.host}}"
                  - op: replace
                    path: /spec/rules/0/http/paths/0/backend/service/name
                    value: "oauth2-{{.id}}"
                  - op: replace
                    path: /spec/tls/0/hosts/0
                    value: "{{.host}}"
                  - op: replace
                    path: /spec/tls/0/secretName
                    value: "oauth2-{{.id}}-tls"
              - target:
                  kind: Service
                patch: |-
                  - op: replace
                    path: /metadata/labels/app
                    value: "oauth2-{{.id}}"
                  - op: replace
                    path: /metadata/name
                    value: "oauth2-{{.id}}"
                  - op: replace
                    path: /spec/externalName
                    value: "{{.target_host}}"
                  - op: replace
                    path: /spec/ports/0/targetPort
                    value: "{{.target_port}}"
      destination:
        server: "https://kubernetes.default.svc"
        namespace: "tooling"
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
