apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oauth2-proxy
  namespace: argocd
spec:
  project: animation
  destination:
    server: https://kubernetes.default.svc
    namespace: tooling
  source:
    # https://github.com/oauth2-proxy/manifests/blob/main/helm/oauth2-proxy/values.yaml
    repoURL: https://oauth2-proxy.github.io/manifests
    targetRevision: 7.7.28
    chart: oauth2-proxy
    helm:
      values: |
        config:
          existingSecret: oauth2-proxy-secret
        envFrom:
          - configMapRef:
              name: oauth2-proxy-configmap
        ingress:
          enabled: true
          path: /
          hosts:
            - oauth.kube-dev.incubateur.net
          annotations:
            kubernetes.io/ingress.class: nginx
            cert-manager.io/cluster-issuer: letsencrypt-prod
            nginx.ingress.kubernetes.io/client-max-body-size: "20M"
            nginx.ingress.kubernetes.io/proxy-body-size: "20M"
          tls:
            - hosts:
                - oauth.kube-dev.incubateur.net
              secretName: oauth-tls-secret

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: false # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
