apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pgs
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - id: test1
        namespace: tooling
  template:
    metadata:
      name: 'pg-{{id}}'
    spec:
      project: tooling
      sources:
        - repoURL: https://charts.bitnami.com/bitnami
          targetRevision: 16.1.0
          chart: postgresql
          # https://artifacthub.io/packages/helm/bitnami/postgresql
          helm:
            # parameters:
            # - name: "nameOverride"
            #   value: '{{id}}'
            # - name: "primary.resourcesPreset"
            #   value: 'small'
            # valuesObject:
            #   nameOverride: '{{id}}'
            #   primary:
            #     resourcesPreset: "small"
            valueFiles:
              - '$values/pgs/{{id}}.values.yaml'
            #ignoreMissingValueFiles: true
        - repoURL: https://github.com/betagouv/kube-dev
          targetRevision: HEAD
          path: pgs
          ref: values
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          selfHeal: true    
        syncOptions:
        - CreateNamespace=true     
