apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pgs
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - id: test1
        namespace: tooling
  template:
    metadata:
      name: 'pg-{{id}}'
    spec:
      project: tooling
      source:
        repoURL: https://charts.bitnami.com/bitnami
        targetRevision: 16.1.0
        chart: postgresql
        # https://artifacthub.io/packages/helm/bitnami/postgresql
        helm:
          valuesObject:
            nameOverride: '{{name}}'
            primary:
              resourcesPreset: "small"
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          selfHeal: true    
        syncOptions:
        - CreateNamespace=true     
