apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pgs
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          # - id: test1
          #   namespace: matomo
          - id: lychee
            namespace: lychee
          - id: matomo-beta
            namespace: matomo
          - id: active-pieces
            namespace: tooling
  template:
    metadata:
      name: "pg-{{id}}"
    spec:
      project: tooling
      sources:
        - repoURL: https://charts.bitnami.com/bitnami
          targetRevision: 16.1.0
          chart: postgresql
          # https://artifacthub.io/packages/helm/bitnami/postgresql
          helm:
            parameters:
              - name: "image.repository"
                value: "bitnamilegacy/postgresql"
              - name: "nameOverride"
                value: "{{id}}"
            valueFiles:
              - "$values/pgs/{{id}}.values.yaml"
            ignoreMissingValueFiles: true
        - repoURL: https://github.com/betagouv/kube-dev
          targetRevision: HEAD
          path: pgs
          ref: values
      destination:
        server: "https://kubernetes.default.svc"
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
