kind: ConfigMap
apiVersion: v1
metadata:
  name: oauth2-pc-proxy-configmap
  namespace: tooling
data:
  # https://oauth2-proxy.github.io/oauth2-proxy/configuration/overview
  OAUTH2_PROXY_HTTP_ADDRESS: "0.0.0.0:4180"
  OAUTH2_PROXY_WHITELIST_DOMAINS: "*.kube-dev.incubateur.net"
  #OAUTH2_PROXY_SCOPE: "read:org user:email"
  # OAUTH2_PROXY_PROVIDER: github
  # OAUTH2_PROXY_GITHUB_TEAM: betagouv
  OAUTH2_PROXY_DISPLAY_NAME: "test-pc provider"
  OAUTH2_PROXY_BANNER: test-pc private access
  OAUTH2_PROXY_FOOTER: test-pc auth
  #OAUTH2_PROXY_EMAIL_DOMAINS: "yopmail.com"
  OAUTH2_PROXY_COOKIE_SECURE: "true"
  OAUTH2_PROXY_COOKIE_DOMAINS: ".kube-dev.incubateur.net"
  OAUTH2_PROXY_CUSTOM_SIGN_IN_LOGO: "https://avatars.githubusercontent.com/u/7874148?s=200&v=4"
  OAUTH2_PROXY_PROVIDER: oidc
  OAUTH2_PROXY_SCOPE: openid given_name usual_name email
  OAUTH2_PROXY_REDIRECT_URL: "https://oauth-pc.kube-dev.incubateur.net/oauth2/callback"
  OAUTH2_PROXY_OIDC_ISSUER_URL: "https://fca.integ01.dev-agentconnect.fr/api/v2" # https://github.com/numerique-gouv/proconnect-documentation/blob/main/resources/valeur_ac_domain.md
  OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: "false"
  OAUTH2_PROXY_PROMPT: "login"
  OAUTH2_PROXY_INSECURE_OIDC_SKIP_NONCE: "false"
  #OAUTH2_PROXY_SHOW_DEBUG_ON_ERROR: "true"
  OAUTH2_PROXY_SKIP_CLAIMS_FROM_PROFILE_URL: "true"
