apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: tooling
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/upstream-vhost: httpbin.org
    nginx.ingress.kubernetes.io/auth-response-headers:
      X-Auth-Request-Email,X-Auth-Request-Preferred-,X-Auth-Request-Access-Token,
      X-Auth-Request-Roles,X-Auth-Request-User,X-Auth-Request-Groups,X-Forwarded-Groups,
      Authorization
    nginx.ingress.kubernetes.io/auth-signin: https://oauth.kube-dev.incubateur.net/oauth2/start?rd=https%3A%2F%2F$host$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-url: https://oauth.kube-dev.incubateur.net/oauth2/auth
  name: proxy-test
spec:
  tls:
    - hosts:
        - proxy-test.kube-dev.incubateur.net
      secretName: proxy-test-tls
  rules:
    - host: proxy-test.kube-dev.incubateur.net
      http:
        paths:
          - backend:
              service:
                name: proxy-test # Here you specify the name of the ExternalName Service traffic must be routed to
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tooling
  name: proxy-test
spec:
  type: ExternalName
  externalName: httpbin.org
